import VMdijs from 'vue-mdijs';
import {
  mdiArchiveOutline,
  mdiMagnify,
  mdiGithub,
  mdiStarOutline,
  mdiPlus,
  mdiLockOutline,
  mdiChevronDown,
  mdiCheck,
  mdiClose,
  mdiStar,
  mdiLinkVariant,
  mdiClipboardOutline,
  mdiDotsHorizontal,
  mdiDeleteOutline,
  mdiSourceFork,
  mdiAccountOutline,
  mdiWeatherNight,
  mdiArrowLeft,
  mdiMenu,
  mdiCloudUploadOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiFolderOutline,
  mdiPencilOutline,
  mdiLogout,
  mdiLogin,
} from '@mdi/js';

VMdijs.add({
  mdiArchiveOutline,
  mdiMagnify,
  mdiGithub,
  mdiStarOutline,
  mdiPlus,
  mdiLockOutline,
  mdiChevronDown,
  mdiCheck,
  mdiClose,
  mdiStar,
  mdiLinkVariant,
  mdiClipboardOutline,
  mdiDotsHorizontal,
  mdiDeleteOutline,
  mdiSourceFork,
  mdiAccountOutline,
  mdiWeatherNight,
  mdiArrowLeft,
  mdiMenu,
  mdiCloudUploadOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiFolderOutline,
  mdiPencilOutline,
  mdiLogout,
  mdiLogin,
});

export default VMdijs;
