[package]
name = "tauri-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc", default-features = false , features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-decorum = { path = "../../../" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
